**NUMPY ARRAYS**

Numpy is a multi dimensional array which is critical for scientific processing in Python

**What is an Array?**

An Array is a data structure that stores values of same data type.In Python this is the main difference between Array and a List. While list can contains elements of different data types, an array can have only single data type.


In [117]:
#pip install numpy # In cmd to install numpy
#conda install numpy #in anaconda prompt

In [68]:
#Importing a numpy

In [69]:
import numpy as np #np is alias


In [70]:
my_lst=[1,2,3,4]
arr=np.array(my_lst) #np.array is used to make numpy arrays

In [71]:
type(arr)

numpy.ndarray

In [72]:
arr #it is a one dimensional array

array([1, 2, 3, 4])

In [73]:
arr.shape # .shape is used to find out the dimensions number of rows and colums

(4,)

In [74]:
arr.reshape(4,1)  #.reshape is used to change dimensions, insert number of rows and colums in the brackets

array([[1],
       [2],
       [3],
       [4]])

In [75]:
#Creating 3 dimensional array manually

In [76]:
my_lst1=[1,2,3]
my_lst2=[4,5,6]
my_lst3=[7,8,9]

In [77]:
arr=np.array([my_lst1,my_lst2,my_lst3]) #use np.array ([lists])

In [78]:
arr #2 dimensional array has two opening and two closing brackets

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr.shape

(3, 3)

In [80]:
arr.reshape(9,1) #reshape can be done by keeping the number of elements the same 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [94]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [95]:
arr #How to update reshaped array?

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Indexing**

In [82]:
#how to retrieve information from the arrays

In [83]:
arr1=np.array([1,2,3,4,5])

In [85]:
arr1[3] #Indexing for one dimensional array

4

In [86]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
#Indexing from two dimensional array
##There is row index and column index both starting from zero

In [91]:
arr[:,:] #picks up all rows and columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [93]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

**Inbuilt Functions**

In [96]:
#arange has three parameters, start, stop and step

In [106]:
arr=np.arange(0,10)

In [107]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
arr=np.arange(0,10,2) #takes a step of 2

In [113]:
arr

array([0, 2, 4, 6, 8])

In [114]:
#linspace provides equi distant points between a given range

In [116]:
np.linspace(1,10,20) #Gives 20 equidistant points between 1 and 10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [118]:
#copy function and broadcasting

In [119]:
arr[3:]=200

In [120]:
arr

array([  0,   2,   4, 200, 200])

In [121]:
arr1=arr

In [122]:
arr1[3:]=500

In [123]:
arr1

array([  0,   2,   4, 500, 500])

In [124]:
arr #replaced array got updated

array([  0,   2,   4, 500, 500])

In [125]:
#To avoid automatic updation use .copy function

In [126]:
arr1=arr.copy()

In [128]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [129]:
arr

array([  0,   2,   4, 500, 500])

In [130]:
arr1

array([   0,    2,    4, 1000, 1000])

In [131]:
#Now we have two different arrays

In [132]:
#Some conditions that are useful in exploratory data analysis

In [136]:
val=2
arr<2

array([ True, False, False, False, False])

In [137]:
arr*2

array([   0,    4,    8, 1000, 1000])

In [138]:
#to get exact elements less than 2

In [140]:
arr[arr<2] #square brackets and condition

array([0])

In [141]:
#To create arrays and reshape

In [143]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [144]:
#np.ones where all the elements are replaced by 1

In [145]:
np.ones(4)

array([1., 1., 1., 1.])

In [148]:
np.ones((5,2),dtype=int) #by default dtype is float

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [149]:
#random distribution

In [151]:
np.random.rand(3,2)

array([[0.33993823, 0.2159476 ],
       [0.17378297, 0.8527086 ],
       [0.15707455, 0.1190943 ]])

In [152]:
#for standard normal distribution use randn

In [153]:
np.random.randn(3,4)

array([[-0.43584618,  1.09716792,  0.26118259, -0.00229886],
       [ 0.06863247,  0.04857904,  0.75546225, -0.5857977 ],
       [-0.6678568 ,  0.52814128, -0.10265844,  0.8965822 ]])

In [154]:
#.randint is to select given number of random numbers from a given range

In [155]:
np.random.randint(1,100,6)

array([58, 28, 69, 72, 76, 74])