**PANDAS**

Pandas is an open source, BSD licensed library providing high performing data structure and data analysis tools for Python programming language

WHat is data frame?

Pandas loads data from csv or any other file and converts into a data frame. For creating data frames use pd.DataFrame function

Data frame consists of combination of rows and columns and data inside it like a table

WHat is data series?

Data series is a data type which is a series of elements taken either from one row or one column

In [6]:
#First import pandas

In [7]:
import pandas as pd
import numpy as np

In [8]:
#creating a data frame
#pd.DataFrame(data,index of rows,index of columns)

In [9]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["c1","c2","c3","c4"])

In [10]:
df.head()

c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [11]:
#to convert this table into an excel sheet use inbuilt function df.to_csv()

In [12]:
df.to_csv("test1.csv")

In [13]:
#accessing the elements there are two ways
# .loc[] (indexed location of a row)
# .iloc[] (indexed location both row and column)

In [16]:
df.loc["row1"]

c1    0
c2    1
c3    2
c4    3
Name: row1, dtype: int32

In [17]:
type(df.loc["row1"]) ##Data type is series

pandas.core.series.Series

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df.iloc[:,:]

c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [18]:
df.iloc[0:2,0:1]

c1
row1   0
row2   4

In [19]:
#Convert data frames into arrays using .values function

In [20]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
df.values.shape

(5, 4)

In [23]:
#To check null condition use df.isnull inbuilt function
#NULL value is not zero, null is NULL

In [25]:
df.isnull().sum() #most frequently used function

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [26]:
df.isnull() #Shows there are no null values

c1     c2     c3     c4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [27]:
#to count number of unique values use .value_count

In [28]:
df.value_counts()

c1  c2  c3  c4
16  17  18  19    1
12  13  14  15    1
8   9   10  11    1
4   5   6   7     1
0   1   2   3     1
dtype: int64

In [29]:
df["c1"].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: c1, dtype: int64

In [30]:
#.unique function is used to find number of unique values

In [33]:
df["c1"].unique()

array([ 0,  4,  8, 12, 16])

In [34]:
#Indexing can also be done by directly calling out a column

In [35]:
df["c1"]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: c1, dtype: int32